# Generated by Django 4.1.5 on 2023-01-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lname',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cnumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mnumber',
            field=models.CharField(max_length=50),
        ),
    ]
