# Generated by Django 4.1.5 on 2023-01-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0003_remove_profile_fname_remove_profile_lname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
