# Generated by Django 4.1.5 on 2023-01-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='conmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnumber', models.CharField(max_length=50)),
                ('ctype', models.CharField(max_length=50)),
                ('cdate', models.CharField(max_length=50)),
                ('occ', models.CharField(max_length=50)),
                ('load', models.CharField(max_length=50)),
                ('hnumber', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
    ]
