# Generated by Django 4.1.5 on 2023-01-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0006_conmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alog',
        ),
        migrations.DeleteModel(
            name='conmodel',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
