# Generated by Django 4.1.1 on 2023-01-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0011_remove_employee_email_remove_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='s@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='hello', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='qwerty', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(default='1', primary_key=True, serialize=False),
        ),
    ]
