# Generated by Django 4.1.1 on 2023-01-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0012_employee_email_employee_name_employee_position_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alog',
        ),
        migrations.DeleteModel(
            name='bill',
        ),
        migrations.DeleteModel(
            name='conmodel',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='feedb',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
