# Generated by Django 4.1.1 on 2023-01-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0021_bill_pstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cnumber',
        ),
    ]
