# Generated by Django 4.1.1 on 2023-01-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0022_remove_profile_cnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pstatus',
            field=models.CharField(default='not paid', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdnumber', models.CharField(max_length=30)),
                ('edate', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=50)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingapp.bill')),
            ],
        ),
    ]
