# Generated by Django 4.1.1 on 2023-01-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0023_alter_bill_pstatus_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='cnumber',
        ),
    ]
