# Generated by Django 4.1.5 on 2023-01-29 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0026_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingapp.conmodel')),
            ],
        ),
    ]
