# Generated by Django 4.1.5 on 2023-02-08 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0032_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedb',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
