# Generated by Django 4.1.5 on 2023-02-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0033_feedb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.FileField(default="{% static 'assets/img/hero-bg.jpg' %}", upload_to='billapp/static/assets/img/profile'),
            preserve_default=False,
        ),
    ]
