# Generated by Django 4.1.5 on 2023-02-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0034_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.FileField(default='no photo', upload_to='billingapp/static/assets/img/profile'),
        ),
    ]
