# Generated by Django 4.1.5 on 2023-02-11 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billingapp', '0039_delete_alog_remove_complaint_conmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='alog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmonth', models.CharField(max_length=50)),
                ('cread', models.IntegerField()),
                ('pread', models.IntegerField()),
                ('tunit', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('ddate', models.CharField(max_length=50)),
                ('pstatus', models.CharField(default='not paid', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='conmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnumber', models.CharField(max_length=50)),
                ('ctype', models.CharField(max_length=50)),
                ('cdate', models.CharField(max_length=50)),
                ('occ', models.CharField(max_length=50)),
                ('load', models.CharField(max_length=50)),
                ('hnumber', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('img', models.FileField(upload_to='billingapp/static/assets/img/profile')),
                ('mnumber', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdnumber', models.CharField(max_length=30)),
                ('edate', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=50)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingapp.bill')),
            ],
        ),
        migrations.CreateModel(
            name='feedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('conmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingapp.conmodel')),
            ],
        ),
        migrations.AddField(
            model_name='conmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingapp.profile'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('conmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingapp.conmodel')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='connmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingapp.conmodel'),
        ),
    ]
