# Generated by Django 4.1.5 on 2023-02-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0045_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alog',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='conmodel',
        ),
        migrations.RemoveField(
            model_name='conmodel',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='feedb',
            name='conmodel',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
        migrations.DeleteModel(
            name='conmodel',
        ),
        migrations.DeleteModel(
            name='feedb',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
